---
name: build

"on":
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          docker pull nesachirou/jlang:latest || true
          make -j build
      - name: Publish
        run: |
          docker login -u nesachirou -p "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          make -j publish
