---
name: test

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup container-structured-test
        run: |
          curl -fsLO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
      - name: Setup yamllint
        run: sudo apt-get install -y --no-install-recommends yamllint
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile
      - name: Build
        run: |
          docker pull nesachirou/jlang:latest || true
          make -j build
      - name: Test
        run: make -j test
